version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install dev dependencies
          command: pip3 install -r dev-requirements.txt
      - run:
          name: Install CI dependencies
          command: pip3 install tox twine
      - python/save-cache
      - run:
          command: flake8
          name: Flake8 / linting
      - run:
          command: tox
          name: Run package tests across all python variants

workflows:
  main:
    jobs:
      - build-and-test

