version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - dev-cache-{{ checksum dev-requirements.txt }}
      - run:
          name: Install dev dependencies
          command: pip3 install -r dev-requirements.txt
      - run:
          name: Install CI dependencies
          command: pip3 install tox twine tox-pyenv
      - run: pyenv install --skip-existing 3.5-dev
      - run: pyenv install --skip-existing 3.6-dev
      - run: pyenv install --skip-existing 3.7-dev
      - run: pyenv install --skip-existing 3.8-dev
      - run: pyenv install --skip-existing 3.9-dev
      - run:
          name: Set local Python versions
          command: pyenv local 3.5-dev 3.6-dev 3.7-dev 3.8-dev 3.9-dev
      - save_cache:
          key: dev-cache-{{ checksum dev-requirements.txt }}
          paths:
            - ~/.pyenv
      - run:
          command: flake8
          name: Flake8 / linting
      - run:
          command: tox
          name: Run package tests across all python variants

workflows:
  main:
    jobs:
      - build-and-test

